
# pull in the parametes for maxim platform
SRCS += $(AD4080_SRC_DIR)/platform/$(PLATFORM)/parameters.c
INCS += $(AD4080_SRC_DIR)/platform/$(PLATFORM)/parameters.h

# pull in platform drivers
AD4080_PLATFORM_SRCS-$(PLATFORM_UART_STDIO) += $(PLATFORM_DRIVERS)/maxim_uart_stdio.c
AD4080_PLATFORM_INCS-$(PLATFORM_UART_STDIO) += $(PLATFORM_DRIVERS)/maxim_uart_stdio.h

AD4080_PLATFORM_SRCS-$(PLATFORM_MAXIM_UART) += $(PLATFORM_DRIVERS)/maxim_uart.c
AD4080_PLATFORM_INCS-$(PLATFORM_MAXIM_UART) += $(PLATFORM_DRIVERS)/maxim_uart.h

AD4080_PLATFORM_SRCS-$(PLATFORM_MAXIM_IRQ) += $(PLATFORM_DRIVERS)/maxim_irq.c
AD4080_PLATFORM_INCS-$(PLATFORM_MAXIM_IRQ) += $(PLATFORM_DRIVERS)/maxim_irq.h

AD4080_PLATFORM_SRCS-$(PLATFORM_MAXIM_DMA) += $(PLATFORM_DRIVERS)/../common/maxim_dma.c
AD4080_PLATFORM_INCS-$(PLATFORM_MAXIM_DMA) += $(PLATFORM_DRIVERS)/../common/maxim_dma.h


SRCS += $(AD4080_PLATFORM_SRCS-y)
INCS += $(AD4080_PLATFORM_INCS-y)

